# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E2224)
$foreground = rgb(EDFEA9)
$color0 = rgb(44484A)
$color1 = rgb(B44743)
$color2 = rgb(617332)
$color3 = rgb(556F89)
$color4 = rgb(8BB80D)
$color5 = rgb(8BB81F)
$color6 = rgb(99BD08)
$color7 = rgb(DDF57C)
$color8 = rgb(9BAC57)
$color9 = rgb(EF5F5A)
$color10 = rgb(829942)
$color11 = rgb(7294B6)
$color12 = rgb(B9F511)
$color13 = rgb(BAF629)
$color14 = rgb(CCFD0B)
$color15 = rgb(DDF57C)
