# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(191616)
$foreground = rgb(FBF2DC)
$color0 = rgb(403D3C)
$color1 = rgb(69605F)
$color2 = rgb(6E6564)
$color3 = rgb(79625C)
$color4 = rgb(826234)
$color5 = rgb(917270)
$color6 = rgb(B7A475)
$color7 = rgb(F1E4C5)
$color8 = rgb(A9A08A)
$color9 = rgb(8C7F7F)
$color10 = rgb(928685)
$color11 = rgb(A2837B)
$color12 = rgb(AD8245)
$color13 = rgb(C19895)
$color14 = rgb(F4DA9C)
$color15 = rgb(F1E4C5)
