# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(14171A)
$foreground = rgb(F4F6ED)
$color0 = rgb(3B3E41)
$color1 = rgb(404C4B)
$color2 = rgb(566D67)
$color3 = rgb(6A726A)
$color4 = rgb(9D9F93)
$color5 = rgb(A8AB9A)
$color6 = rgb(A8AB9A)
$color7 = rgb(E7E9DD)
$color8 = rgb(A2A39B)
$color9 = rgb(566564)
$color10 = rgb(729189)
$color11 = rgb(8D988E)
$color12 = rgb(D1D3C3)
$color13 = rgb(E0E4CD)
$color14 = rgb(E0E4CD)
$color15 = rgb(E7E9DD)
