# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D0D1D0
background         #0A130B
cursor             #7C727A

active_tab_foreground     #0A130B
active_tab_background     #D0D1D0
inactive_tab_foreground   #D0D1D0
inactive_tab_background   #0A130B

active_border_color   #D0D1D0
inactive_border_color #0A130B
bell_border_color     #A2A0A6

color0      #9C9D9C
color1		#A2A0A6
color2		#BB9350
color3		#AC5B43
color4		#7F6441
color5		#71646C
color6		#785F3E
color7		#616063
color8		#97959B
color9		#D8D5DD
color10		#F9C46A
color11		#E57A59
color12		#AA8657
color13		#968590
color14		#A17E53
color15		#E3E1E5
