# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B4DAF1
background         #17171D
cursor             #627C96

active_tab_foreground     #17171D
active_tab_background     #B4DAF1
inactive_tab_foreground   #B4DAF1
inactive_tab_background   #17171D

active_border_color   #B4DAF1
inactive_border_color #17171D
bell_border_color     #0B1025

color0      #3E3E45
color1		#0B1025
color2		#0C162D
color3		#154063
color4		#19487B
color5		#1E6A99
color6		#1F70A0
color7		#8CC2E2
color8		#62889E
color9		#0E1632
color10		#101E3C
color11		#1C5684
color12		#2260A4
color13		#288ECC
color14		#2A96D6
color15		#8CC2E2
