# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DDE0E1
background         #103119
cursor             #6F8624

active_tab_foreground     #103119
active_tab_background     #DDE0E1
inactive_tab_foreground   #DDE0E1
inactive_tab_background   #103119

active_border_color   #DDE0E1
inactive_border_color #103119
bell_border_color     #99BD08

color0      #AFB3B6
color1		#99BD08
color2		#8BB81F
color3		#8BB80D
color4		#556F89
color5		#617332
color6		#B44743
color7		#5C7205
color8		#8FB107
color9		#CCFD0B
color10		#BAF629
color11		#B9F511
color12		#7294B6
color13		#829942
color14		#EF5F5A
color15		#DDF57C
