# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates
# ========================================
# CUSTOM WINDOW RULES - piletteloic
# ========================================

# Discord - Workspace 7 (IM/Communication)
windowrule = workspace 7, match:tag im*

# Spotify - Workspace 4 (Multimedia)
windowrule = workspace 4, match:tag multimedia*
windowrule = tag +multimedia, match:class ^([Ss]potify)$

