-- Generated by nwg-displays on 2026-09-01 at 09:07:00. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "2966x1080",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1
})
