-- Generated by nwg-displays on 2026-09-01 at 09:08:39. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "4620x1080",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "3391x0",
    scale = 1
})
