
name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint requests

    - name: Get changed Python files
      run: |
        # Get a list of all modified .py files in the commit
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$')
        echo "Changed files: $CHANGED_FILES"
        echo "$CHANGED_FILES" > changed_files.txt

    - name: Analysing the modified Python files with pylint
      run: |
        # Read the list of changed files and run pylint only on those
        if [ -f changed_files.txt ]; then
          CHANGED_FILES=$(cat changed_files.txt)
          if [ ! -z "$CHANGED_FILES" ]; then
            pylint $CHANGED_FILES
          else
            echo "No Python files changed, skipping pylint."
          fi
        fi

